title: Blog Bibliotheks- und Archivinformatik
author: Ines Trezzini
description: > # this means to ignore newlines
  Vorlage f√ºr ein Lerntagebuch im Kurs Bibliotheks- und Archivinformatik FS2020

# social links
github_username:  TrezziniInes # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
